### ISSUE TITLE
Implement the pre-made controls.

### ISSUE THREAD

**Issue by thebearingedge** [thebearingedge/controlled-components#2]
This library should include some pre-made form controls.
- [x] `Hidden`
- [x] `Input` (generic, pass a `type` prop)
- [x] `TextArea`
- [x] `Select`
- [x] `Text (input[type="text"])`
- [x] `Checkbox (input[type="checkbox"])`
- [x] `RadioGroup`
  - [x] `Radio`
- [x] `SelectMultiple` 🔥 
- [x] `FieldSet` 💪 
- [x] `FieldArray` 💀 
- [x] Consider refactoring `createControl` into a simple `Field` component _a la_ redux-form.
- [x] Decouple field-model factories from the form component (for tree shaking and de-duplicating code).

**Comment by thebearingedge** [comment]
### `Input`

```jsx
const Input = controlled('input')({
  defaultProps: {
    type: 'text',
    value: 'hello world'
  }
})

render(<Input name='foo'/>)

/*
  <input type='text' name='foo' value='hello world' onChange={[Function]} onBlur={[Function]}/>
*/
```

**Comment by thebearingedge** [comment]
### `Message`

```jsx
import Message from 'controlled-components/message'

render(
  <Message name='foo'>
    { ({ message }) => <span>{ message }</span> }
  </Message>
)

/*
  <span>A validation message from field "foo".</span>
*/
```

**Comment by thebearingedge** [comment]
```jsx
import controlled from 'controlled-components'

const Input = controlled(({ id, label, ...props }) =>
  <div className='form-group'>
    <label htmlFor={id}>{ label }</label>
    <input type="text" id={id} className='form-control' {...props}/>
  </div>
, {
  displayName: 'Input',
  defaultProps: {
    value: ''
  }
})
```

**Comment by thebearingedge** [comment]
### createMessage

```jsx
import { createMessage } from 'controlled-components'

const InvalidAge = createMessage(({ error }) =>
  <div className='alert alert-danger' role='alert'>
    { error }
  </div>
)({
  displayName: 'InvalidAge'
  validate: ({ age }) => age < 21 && 'You are too young. I cannot help you.'
})

render(<InvalidAge/>)

/**
 * <div class="alert alert-danger" role="alert">
 *   You are too young, I cannot help you.
 * </div>
 */
```

**Comment by MouseZero** [comment]
# createMessage (Multi Field Validate)
```jsx
import { createMessage } from 'controlled-components'

const InvalidSchedule = createMessage(({ error }) =>
  <div className='alert alert-danger' role='alert'>
    { error }
  </div>
)({
  displayName: 'InvalidSchedule'
  validateFields: ['checkIn', 'checkOut'],
  validate: ({ checkIn, checkOut }) => checkIn >= checkOut && 'Check in date must be before check out date'
})

render(<InvalidAge/>)

/**
 * <div class="alert alert-danger" role="alert">
 *   Check in date must be before check out date
 * </div>
 */
```

**Comment by thebearingedge** [comment]
What about this?

import { createMessage } from 'controlled-components'

const InvalidSchedule = createMessage(({ error }) =>
  <div className='alert alert-danger' role='alert'>
    { error }
  </div>
)({
  displayName: 'InvalidSchedule'
  fields: ['checkIn', 'checkOut'],
  error: ({ checkIn, checkOut }) => checkIn >= checkOut && 'Check in date must be before check out date'
})

render(<InvalidSchedule/>)

/**
 * <div class="alert alert-danger" role="alert">
 *   Check in date must be before check out date
 * </div>
 */
```

**Comment by MouseZero** [comment]
Whats the advantage to the curry?

**Comment by MouseZero** [comment]
ya thats probably more clear

**Comment by thebearingedge** [comment]
>Whats the advantage to the curry?

I can't remember my exact motive, but currying creates seams in the code for reuse and testability.

>Will "validate" be passed the full field value object? looks like in "createMessage" but I want to make sure my assumption is correct.

I don't think it should, I think asking for fields explicitly should be our default.

**Comment by MouseZero** [comment]
Is error the right right name? Because a createMessage could also be a hint that shows and hides based off of a function?

**Comment by MouseZero** [comment]
the word error is the best for reasoning about and error but do we also allow for "validate" type functions under another name for the other use cases?

**Comment by thebearingedge** [comment]
> Is error the right right name? Because a createMessage could also be a hint that shows and hides based off of a function?

Agreed.

```jsx
import { createMessage } from 'controlled-components'

const InvalidSchedule = createMessage(({ message }) =>
  <div className='alert alert-danger' role='alert'>
    { message.error }
  </div>
)({
  displayName: 'InvalidSchedule',
  message: {
    error: {
      fields: ['checkIn', 'checkOut'],
      validate: ({ checkIn, checkOut }) => checkIn >= checkOut && 'Check in date must be before check out date'
    }
  }
})

render(<InvalidSchedule/>)

/**
 * <div class="alert alert-danger" role="alert">
 *   Check in date must be before check out date
 * </div>
 */
```

**Comment by thebearingedge** [comment]
So the property is arbitrarily chosen by the developer and, if they really want to, they can have any combo of `hint`, `error`, whatever. We don't have to care.

**Comment by MouseZero** [comment]
yes this works and its nice if you want to bundle some things like hints and errors

**Comment by thebearingedge** [comment]
It might be nicer to use if we just give them all form values.

```jsx
const InvalidSchedule = createMessage(({ message }) =>
  <div>
    { message.error &&
      <div className='alert alert-danger' role='alert'>
        { message.error }
      </div>
    }
    { message.info &&
      <div className='alert alert-info' role='alert'>
        { message.info }
      </div>
    }
  </div>
)({
  displayName: 'InvalidSchedule',
  message: {
    error: ({ checkIn, checkOut }) => checkIn >= checkOut && 'Check in date must be before check out date'
    info: ({ checkIn }) => checkIn < Date.now() && 'You are a wizard...'
  }
})
```

**Comment by thebearingedge** [comment]
This makes it possible to mix them if you really want to and it's not crazy verbose.

**Comment by thebearingedge** [comment]
I'm not completely in love with the term "message". Here's a possible alternative.

```jsx
import { createHint } from 'controlled-compnents'

const InvalidSchedule = createHint(({ messages }) =>
  <div>
    { messages.error &&
      <div className='alert alert-danger' role='alert'>
        { messages.error }
      </div>
    }
    { messages.info &&
      <div className='alert alert-info' role='alert'>
        { messages.info }
      </div>
    }
  </div>
)({
  displayName: 'InvalidSchedule',
  messages: {
    error: ({ checkIn, checkOut }) => checkIn >= checkOut && 'Check in date must be before check out date'
    info: ({ checkIn }) => checkIn < Date.now() && 'You are a wizard...'
  }
})
```

**Comment by thebearingedge** [comment]
And maybe we could support the basic case too?

```jsx
const InvalidSchedule = createHint(({ hint }) =>
    <div className='alert alert-danger' role='alert'>
      { hint }
    </div>
)({
  displayName: 'InvalidSchedule',
  hint: ({ checkIn }) => checkIn < Date.now() && 'You are a wizard...'
})
```

**Comment by MouseZero** [comment]
How does "Form" know what "hint" wants or does it get the entire fields object?

**Comment by thebearingedge** [comment]
🤔 good question. maybe it should be constrained to specify at that point?

```jsx
const InvalidSchedule = createHint(({ hint }) =>
    <div className='alert alert-danger' role='alert'>
      { hint }
    </div>
)({
  displayName: 'InvalidSchedule',
  field: 'checkIn',
  hint: checkin => checkIn < Date.now() && 'You are a wizard...'
})
```

**Comment by MouseZero** [comment]
But I agree with this for something like an Input field. Where you implicitly get your own fields value. That you can then validate.

**Comment by MouseZero** [comment]
As in something like this
```jsx
const Input = controlled('createControl',
)({
  displayName: 'CheckIn',
  hint: myField => myField > Date.now() && 'You are a wizard...'
})
```

**Comment by thebearingedge** [comment]
Yeah, we'll definitely need to play around with this. One of my goals with the public API is that we use it internally to create our pre-fabbed components.

This should work too.

```jsx
import Hint from 'controlled-components/hint'

render(<Hint field='checkIn'/>)
```

**Comment by MouseZero** [comment]
I really like that.

**Comment by thebearingedge** [comment]
So altogether something like this.

```jsx
import Form from 'controlled-components/form'
import Hint from 'controlled-components/hint'
import Input from 'controlled-components/input'

const handleSubmit = (values) => {
  console.log(values)
}

const hintUsername = username => {
  return !!username.trim() && 'Please fill out your name'.
}

render(
  <Form onSubmit={handleSubmit}>
    <label htmlFor='username'>Username</label>
    <Input name='username' hint={hintUsername}/>
    <Hint field='username'/>
  </Form>
)
```

**Comment by thebearingedge** [comment]
Invalid:

```html
<form>
  <label for="username">Username</label>
  <input type="text" id="username" name="username" value=""/>
  Please fill out your name.
</form>
```

Valid:
```html
<form>
  <label for="username">Username</label>
  <input type="text" id="username" name="username" value="Russell"/>
</form>
```

**Comment by MouseZero** [comment]
Why is plain text invalid?

**Comment by thebearingedge** [comment]
Fixed.

**Comment by thebearingedge** [comment]
BANG BANG BANG

**Comment by MouseZero** [comment]
Are we compassable just like normal react? so you can use something like this over the stock components?
```jsx
const EmailField = createControlled(() => (
    <label htmlFor='email'>Email</label>
    <Input name='username' hint={hintUsername}/>
    <Hint field='username'/>
))({
  displayName: someVar,
  hint: myField => someValidation(myFiled)
})
```

**Comment by thebearingedge** [comment]
No, this might "work" but as it is now, there would be four layers of HOC.

- Field
  - Control
    - Field
      - Control
    - Field
      - Control

**Comment by thebearingedge** [comment]
But something like this might.

```jsx
const EmailField = createControlled(({ field, ...props }) => (
    <label htmlFor='email'>Email</label>
    <input {...props}/>
    <Hint field='username'/>
))({
  displayName: 'EmailField',
  hint: email => someValidation(email)
})
```

**Comment by thebearingedge** [comment]
I guess I'm not super clear what you mean, but nesting Controls is probably a bad idea.

**Comment by MouseZero** [comment]
You answered what I was looking for.

**Comment by MouseZero** [comment]
Ok so I'm trying to wrap my head around conditional rendering for things without the use of props. What do you think the best way to get the value of other fields is. Something like this?

```jsx
import { Form, Select } from 'conrolled-components'

const CarModelSelect = createControlled(({fields}) => (
    <select>
        {fields.carMake === 'toyota' && (
            <option value='camry'>Camry</option>
            <option value='corolla'>Corolla</option>
        )}
        {fields.carMake === 'hyndai' && (
            <option value='elantra'>Eleantra</option>
            <option value='genesis'>Genesis</option>
        )}
    </select>
))({
    displayName: 'CarModel',
    getFields: ['carMake']
})

render(
    <Form>
        <Select id name='carMake'>
            <option value='toyota'>Toyota</option>
            <option value='hyundai'>Hyundai</option>
        </Select>
        <CarModelSelect/>
    </Form>
)
```

**Comment by MouseZero** [comment]
There's probably invalid code in here I was just trying to throw something up that roughly made sense.

**Comment by MouseZero** [comment]
Or do you as a user grab it from context directly? I think I rather not do that.

**Comment by MouseZero** [comment]
Oh shoot you would have to rerender if the value changed so this issue is very related to the messages problem we solved. But inputs don't get a triggered rerender when fields change :(

**Comment by MouseZero** [comment]
There is a lot of different concerns on this thread I'll try to move this out somewhere else.

**Comment by thebearingedge** [comment]
I decided to abandon the passing a `String` to `createControl`. It got too ugly when I tried to incorporate radio buttons.

**Comment by MouseZero** [comment]
So given all we talked about regarding props this is roughly what I picture.

#### Idea
##### field
- access to all of the fields
- way to query fields status example (touched, dirty ...)
##### form
- function for requesting a given field validates
##### message
- Object that takes validation functions
    - these functions get a "fields" as the first argument

#### Objects
```js
// field
////////////////////////////
{
    foo1: {
        value: 'some value',
        touched: true,
        dirty: true,
        settings: {
            touchable: true
        }
    },
    foo2: {
        value: 'some other value',
        dirty: false,
        settings: {
            touchable: false
        }
    },
}

// form
////////////////////////////
{
    validate: (fieldName) => {/*some code*/},
    setttings: {
        touchable: true,
    }
}

// message
////////////////////////////
// user specified keys for validation functions
{
    hint: fields => fields.age > 18 ? 'Are you sure' : null
    error: fields => fields.age > 21 ? 'You are to young' : null
}
```

**Comment by MouseZero** [comment]
Feel free to fill that in with things I'm missing.

**Comment by MouseZero** [comment]
shoot messages doesn't belong in props right thats for contracting the component

**Comment by thebearingedge** [comment]
It looks like you have the idea.

But now that I'm thinking about it, we should be _super_ careful to stick to real scenarios to justify a larger API surface. I could be wrong, but I feel like some of the features of [Redux Form's fields](https://redux-form.com/7.1.2/docs/api/field.md/) were added just because someone realized it was possible, not because it was needed.

**Comment by thebearingedge** [comment]
![radio-group](https://user-images.githubusercontent.com/7432943/32817844-de911062-c974-11e7-88ce-6c6624dfe068.gif)

**Comment by thebearingedge** [comment]
<img width="1680" alt="screenshot 2017-11-14 19 53 08" src="https://user-images.githubusercontent.com/7432943/32817981-8425278e-c975-11e7-8e2f-efc1a9c1bd3a.png">

**Comment by thebearingedge** [comment]
I broke down and [snagged the name](https://www.npmjs.com/package/controlled-components). Do you have an NPM account? I can add you to the collaborators list.

**Comment by thebearingedge** [comment]
I'd like to build a large JavaScript quiz with this for fun, profit, and measuring perf. If you can think of any questions, lemme know.

**Comment by MouseZero** [comment]
I just created one mouse-zero

**Comment by thebearingedge** [comment]
<img width="1047" alt="screenshot 2017-11-24 19 02 14" src="https://user-images.githubusercontent.com/7432943/33226791-181d72e4-d14a-11e7-9002-1154389494ec.png">

**Comment by thebearingedge** [comment]
![controlled](https://user-images.githubusercontent.com/7432943/33466217-55f66d12-d601-11e7-8423-e190ce9fdd24.gif)

**Comment by thebearingedge** [comment]
I decided not to implement pre-made controls for now, but the underlying infrastructure is there now.
