### ISSUE TITLE
Design the message API.

### ISSUE THREAD

**Issue by MouseZero** [thebearingedge/controlled-components#3]
## Problem
Controlled does not get notified if another field is change which can be an issue if its render output depends on said field

### Maybe use a "Message" "Controlled" Hybrid
Unlike a normal "message" which gives you the results of a function you would want a field value directly.

### Maybe create something like the following in the api
```jsx
import { Form, Select } from 'conrolled-components'

const CarModelSelect = createControlled(({fields}) => (
    <select>
        {fields.carMake === 'toyota' && (
            <option value='camry'>Camry</option>
            <option value='corolla'>Corolla</option>
        )}
        {fields.carMake === 'hyndai' && (
            <option value='elantra'>Elantra</option>
            <option value='genesis'>Genesis</option>
        )}
    </select>
))({
    displayName: 'CarModel',
    fields: ['carMake']
})

render(
    <Form>
        <Select id name='carMake'>
            <option value='toyota'>Toyota</option>
            <option value='hyundai'>Hyundai</option>
        </Select>
        <CarModelSelect/>
    </Form>
)
```

**Comment by thebearingedge** [comment]
I like this. I'm thinking we'll expose some models to controls and messages. Maybe a `control` and a `form`.

**Comment by thebearingedge** [comment]
Right now I'm leaning more towards this. Any ideas on what properties/methods should be exposed on `field`, `form`, and `message`?

```jsx
const CustomInput = createControl(({ field, form, ...props }) =>
  // some code
)({
  displayName: 'CustomInput'
})

const CustomMessage = createMessage(({ field, form, message, ...props }) =>
  // some code
)({
  displayName: 'CustomMessage'
})
```

**Comment by MouseZero** [comment]
This is less verbose I do like it. We should have a way to access status from the "fields" object that the validation function receives.

**Comment by MouseZero** [comment]
status meaning touched, dirty ...

**Comment by thebearingedge** [comment]
Yeah, I think that `form` prop would have all that stuff. Like `fields.foo.isTouched` or `fields.foo.value` or even `form.foo.setDirty()`. I was thinking it'd be called `fields`, but wrote `form` instead.

**Comment by thebearingedge** [comment]
Superseded by #14
